#' Optimal Linear Allocation based on dtgch cbem4 solved by solin relow, multiple rhos, collected
#'
#' Generated by *\url{https://fanwangecon.github.io/PrjOptiAlloc/articles/ffv_opt_anlyz_rhgin.html}*, opti allocate and expected outcome, many rhos
#'
#' @docType data
#'
#' @usage data(df_opt_dtgch_cbem4_rrlop_allrh)
#'
#' @format csv
#'
#' @keywords datasets
#'
#' @references “Early life height and weight production functions with endogenous energy and protein inputs”, September 2016, 65-81, Economics & Human Biology, 22, Esteban Puentes, Fan Wang, Jere R. Behrman, Flavio Cunha, John Hoddinott, John A. Maluccio, Linda S. Adair, Judith Borja and Reynaldo Martorell
#'
#' @source \url{https://www.sciencedirect.com/science/article/pii/S1570677X16300107}
#'
#' @examples
#' data(df_opt_dtgch_cbem4_rrlop_allrh)
#' # Print
#' head(df_opt_dtgch_cbem4_rrlop_allrh, 10)
#' head(df_opt_dtgch_cbem4_rrlop_allrh[,10:17], 1100)
"df_opt_dtgch_cbem4_rrlop_allrh"
