#' Optimal Linear Allocation dtgch cbem4, solin relow, multiple rhos, GINI
#'
#' Generated by *\url{https://fanwangecon.github.io/PrjOptiAlloc/articles/ffv_opt_solin_relow.html}*, opti allocate and expected outcome
#'
#' @docType data
#'
#' @usage data(df_opt_dtgch_cbem4_rrlop_argin)
#'
#' @format csv
#'
#' @keywords datasets
#'
#' @references “Early life height and weight production functions with endogenous energy and protein inputs”, September 2016, 65-81, Economics & Human Biology, 22, Esteban Puentes, Fan Wang, Jere R. Behrman, Flavio Cunha, John Hoddinott, John A. Maluccio, Linda S. Adair, Judith Borja and Reynaldo Martorell
#'
#' @source \url{https://www.sciencedirect.com/science/article/pii/S1570677X16300107}
#'
#' @examples
#' data(df_opt_dtgch_cbem4_rrlop_argin)
#' print(as.matrix(df_opt_dtgch_cbem4_rrlop_argin))
"df_opt_dtgch_cbem4_rrlop_argin"
